"""
MTGJSON TypedDict sub-models.

These are lightweight dict-based types used as nested structures
in card and set models. Using TypedDict instead of BaseModel
for ~2.5x faster parsing performance.
"""

from __future__ import annotations

from typing_extensions import Required, TypedDict  # noqa: UP035

# =============================================================================
# Core Card Sub-Models
# =============================================================================


class ForeignDataIdentifiers(TypedDict, total=False):
    """Identifiers for foreign card data."""

    multiverseId: str
    scryfallId: str


class ForeignData(TypedDict, total=False):
    """Localized card data."""

    __doc_title__ = "Foreign Data"
    __doc_desc__ = "The Foreign Data Data Model describes the properties for a card in alternate languages."
    __doc_parent__ = (
        "**Parent model:** [Card (Atomic)](/data-models/card/card-atomic/), "
        "[Card (Deck)](/data-models/card/card-deck/), "
        "[Card (Set)](/data-models/card/card-set/)\n"
        "- **Parent property:** `foreignData`"
    )
    __doc_enum__ = "foreignData"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, foreign data"
    __field_docs__ = {
        "faceName": {
            "description": "The foreign name on the face of the card.",
            "introduced": "v5.0.1",
            "optional": True,
        },
        "flavorText": {
            "description": "The foreign flavor text of the card.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "identifiers": {
            "description": "The identifiers associated to a card. See the [Identifiers](/data-models/identifiers/) Data Model.",
            "introduced": "v5.2.2",
            "type_override": "Identifiers",
        },
        "language": {
            "description": "The foreign language of card.",
            "introduced": "v4.0.0",
            "enum_key": "language",
        },
        "name": {
            "description": "The foreign name of the card.",
            "introduced": "v4.0.0",
        },
        "text": {
            "description": "The foreign text of the card.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "type": {
            "description": "The foreign type of the card, including any supertypes and subtypes, and are given a `-` delimiter if appropriate.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "uuid": {
            "description": "The universal unique identifier (v5) generated by MTGJSON.",
            "introduced": "v5.2.2",
        },
    }

    faceName: str
    flavorText: str
    identifiers: Required[ForeignDataIdentifiers]
    language: Required[str]
    multiverseId: int  # Deprecated - top level multiverse ID
    name: Required[str]
    text: str
    type: str
    uuid: Required[str]


class Identifiers(TypedDict, total=False):
    """External identifiers for a card or sealed product."""

    __doc_title__ = "Identifiers"
    __doc_desc__ = "The Identifiers Data Model describes the properties of identifiers associated to a card or product."
    __doc_parent__ = (
        "**Parent model:** [Card (Deck)](/data-models/card/card-deck/), "
        "[Card (Set)](/data-models/card/card-set/), "
        "[Card (Token)](/data-models/card/card-token/), "
        "[Sealed Product](/data-models/sealed-product/)\n"
        "- **Parent property:** `identifiers`"
    )
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, identifiers"
    __field_docs__ = {
        "abuId": {
            "description": "The [ABUGames](https://abugames.com/) identifier.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "cardKingdomEtchedId": {
            "description": "The [Card Kingdom](https://www.cardkingdom.com/?partner=mtgjson&utm_source=mtgjson&utm_medium=affiliate&utm_campaign=mtgjson) etched card identifier.",
            "introduced": "v5.2.0",
            "optional": True,
        },
        "cardKingdomFoilId": {
            "description": "The [Card Kingdom](https://www.cardkingdom.com/?partner=mtgjson&utm_source=mtgjson&utm_medium=affiliate&utm_campaign=mtgjson) foil card identifier.",
            "introduced": "v5.0.0",
            "optional": True,
        },
        "cardKingdomId": {
            "description": "The [Card Kingdom](https://www.cardkingdom.com/?partner=mtgjson&utm_source=mtgjson&utm_medium=affiliate&utm_campaign=mtgjson) card identifier.",
            "introduced": "v5.0.0",
            "optional": True,
        },
        "cardsphereId": {
            "description": "The [Cardsphere](https://www.cardsphere.com/) card identifier.",
            "introduced": "v5.2.1",
            "optional": True,
        },
        "cardsphereFoilId": {
            "description": "The [Cardsphere](https://www.cardsphere.com/) foil card identifier.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "cardtraderId": {
            "description": "The [Card Trader](https://www.cardtrader.com/en) card identifier.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "csiId": {
            "description": "The [CoolStuffInc](https://www.coolstuffinc.com/) identifier.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "mcmId": {
            "description": "The [Cardmarket](https://www.cardmarket.com/en/Magic?utm_campaign=card_prices&utm_medium=text&utm_source=mtgjson) card identifier.",
            "introduced": "v4.4.0",
            "optional": True,
        },
        "mcmMetaId": {
            "description": "The [Cardmarket](https://www.cardmarket.com/en/Magic?utm_campaign=card_prices&utm_medium=text&utm_source=mtgjson) card meta identifier.",
            "introduced": "v4.4.0",
            "optional": True,
        },
        "miniaturemarketId": {
            "description": "The [Miniature Market](https://www.miniaturemarket.com/) identifier.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "mtgArenaId": {
            "description": "The [Magic: The Gathering Arena](https://magic.wizards.com/en/mtgarena) card identifier.",
            "introduced": "v4.5.0",
            "optional": True,
        },
        "mtgjsonFoilVersionId": {
            "description": "The universal unique identifier (v4) generated by MTGJSON for the foil version of the card.",
            "introduced": "v5.2.1",
            "optional": True,
        },
        "mtgjsonNonFoilVersionId": {
            "description": "The universal unique identifier (v4) generated by MTGJSON for the non-foil version of the card.",
            "introduced": "v5.2.1",
            "optional": True,
        },
        "mtgjsonV4Id": {
            "description": "The universal unique identifier (v4) generated by MTGJSON.",
            "introduced": "v5.0.0",
            "optional": True,
        },
        "mtgoFoilId": {
            "description": "The [Magic: The Gathering Online](https://magic.wizards.com/en/mtgo) card foil identifier.",
            "introduced": "v4.5.0",
            "optional": True,
        },
        "mtgoId": {
            "description": "The [Magic: The Gathering Online](https://magic.wizards.com/en/mtgo) card identifier.",
            "introduced": "v4.5.0",
            "optional": True,
        },
        "multiverseId": {
            "description": "The [Wizards of the Coast](https://company.wizards.com) card identifier used in conjunction with [Gatherer](https://gatherer.wizards.com).",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "scgId": {
            "description": "The [StarCityGames](https://starcitygames.com/) identifier.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "scryfallId": {
            "description": "The universal unique identifier generated by [Scryfall](https://scryfall.com/). Note that cards with multiple faces are not unique.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "scryfallCardBackId": {
            "description": "The universal unique identifier generated by [Scryfall](https://scryfall.com/) for the back face of a card.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "scryfallOracleId": {
            "description": "The unique identifier generated by [Scryfall](https://scryfall.com/) for this card's oracle identity. This value is consistent across reprinted card editions, and unique among different cards with the same name (Un-sets, tokens, etc).",
            "introduced": "v4.3.1",
            "optional": True,
        },
        "scryfallIllustrationId": {
            "description": "The unique identifier generated by [Scryfall](https://scryfall.com/) for the card artwork that remains consistent across reprints. Newly previewed cards may not have this property yet.",
            "introduced": "v4.3.1",
            "optional": True,
        },
        "tcgplayerProductId": {
            "description": "The [TCGplayer](https://www.tcgplayer.com?partner=mtgjson&utm_campaign=affiliate&utm_medium=mtgjson&utm_source=mtgjson) card identifier.",
            "introduced": "v4.2.1",
            "optional": True,
        },
        "tcgplayerEtchedProductId": {
            "description": "The [TCGplayer](https://www.tcgplayer.com?partner=mtgjson&utm_campaign=affiliate&utm_medium=mtgjson&utm_source=mtgjson) etched card identifier.",
            "introduced": "v5.2.0",
            "optional": True,
        },
        "tntId": {
            "description": "The [Troll and Toad](https://www.trollandtoad.com/) identifier.",
            "introduced": "v5.2.2",
            "optional": True,
        },
    }

    # Sealed product identifiers
    abuId: str
    cardtraderId: str
    csiId: str
    miniaturemarketId: str
    mvpId: str
    scgId: str
    tntId: str
    # Card identifiers
    cardKingdomEtchedId: str
    cardKingdomFoilId: str
    cardKingdomId: str
    cardsphereId: str
    cardsphereFoilId: str
    deckboxId: str
    mcmId: str
    mcmMetaId: str
    mtgArenaId: str
    mtgjsonFoilVersionId: str
    mtgjsonNonFoilVersionId: str
    mtgjsonV4Id: str
    mtgoFoilId: str
    mtgoId: str
    multiverseId: str
    scryfallId: str
    scryfallCardBackId: str
    scryfallIllustrationId: str
    scryfallOracleId: str
    tcgplayerEtchedProductId: str
    tcgplayerProductId: str


class LeadershipSkills(TypedDict):
    """Commander/Brawl/Oathbreaker legality."""

    __doc_title__ = "Leadership Skills"
    __doc_desc__ = "The Leadership Skills Data Model describes the properties of formats that a card is legal to be your Commander in play formats that utilize Commanders."
    __doc_parent__ = (
        "**Parent model:** [Card (Atomic)](/data-models/card/card-atomic/), "
        "[Card (Deck)](/data-models/card/card-deck/), "
        "[Card (Set)](/data-models/card/card-set/)\n"
        "- **Parent property:** `leadershipSkills`"
    )
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, leadership skills"
    __field_docs__ = {
        "brawl": {
            "description": "If the card can be your commander in the [Standard Brawl](https://magic.wizards.com/en/game-info/gameplay/formats/brawl) format.",
            "introduced": "v4.5.1",
        },
        "commander": {
            "description": "If the card can be your commander in the [Commander/EDH](https://magic.wizards.com/en/content/commander-format) format.",
            "introduced": "v4.5.1",
        },
        "oathbreaker": {
            "description": "If the card can be your commander in the [Oathbreaker](https://oathbreakermtg.org/) format.",
            "introduced": "v4.5.1",
        },
    }

    brawl: bool
    commander: bool
    oathbreaker: bool


class Legalities(TypedDict, total=False):
    """Format legalities for a card."""

    __doc_title__ = "Legalities"
    __doc_desc__ = (
        "The Legalities Data Model describes the properties of legalities of a card in various game play formats."
    )
    __doc_parent__ = (
        "**Parent model:** [Card (Atomic)](/data-models/card/card-atomic/), "
        "[Card (Deck)](/data-models/card/card-deck/), "
        "[Card (Set)](/data-models/card/card-set/)\n"
        "- **Parent property:** `legalities`"
    )
    __doc_enum__ = "legalities"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, legalities"
    __field_docs__ = {
        "alchemy": {
            "description": "Legality of the card in the [Alchemy](https://magic.wizards.com/en/mtgarena/alchemy) play format.",
            "introduced": "v5.1.0",
            "optional": True,
        },
        "brawl": {
            "description": "Legality of the card in the [Brawl](https://magic.wizards.com/en/formats/brawl) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "commander": {
            "description": "Legality of the card in the [Commander](https://magic.wizards.com/en/formats/commander) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "duel": {
            "description": "Legality of the card in the [Duel Commander](https://magic.wizards.com/en/formats/commander-1v1) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "explorer": {
            "description": "Legality of the card in the [Explorer](https://magic.wizards.com/en/formats/explorer) play format.",
            "introduced": "v5.2.1",
            "optional": True,
        },
        "future": {
            "description": "Legality of the card in the future for the [Standard](https://magic.wizards.com/en/formats/standard) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "gladiator": {
            "description": "Legality of the card in the [Gladiator](https://gladiator.blog/about-gladiator/) play format.",
            "introduced": "v5.2.0",
            "optional": True,
        },
        "historic": {
            "description": "Legality of the card in the [Historic](https://magic.wizards.com/en/formats/historic) play format.",
            "introduced": "v5.1.0",
            "optional": True,
        },
        "historicbrawl": {
            "description": "Legality of the card in the [Historic Brawl](https://draftsim.com/mtg-arena-historic-brawl/) play format.",
            "introduced": "v5.2.0",
            "optional": True,
        },
        "legacy": {
            "description": "Legality of the card in the [Legacy](https://magic.wizards.com/en/formats/legacy) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "modern": {
            "description": "Legality of the card in the [Modern](https://magic.wizards.com/en/formats/modern) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "oathbreaker": {
            "description": "Legality of the card in the [Oathbreaker](https://magic.wizards.com/en/formats/oathbreaker) play format.",
            "introduced": "v5.2.0",
            "optional": True,
        },
        "oldschool": {
            "description": "Legality of the card in the [Old School](https://mtg.wiki/page/Old_School) play format.",
            "introduced": "v5.2.0",
            "optional": True,
        },
        "pauper": {
            "description": "Legality of the card in the [Pauper](https://magic.wizards.com/en/formats/pauper) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "paupercommander": {
            "description": "Legality of the card in the [Pauper Commander](https://mtg.wiki/page/Pauper_Commander) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "penny": {
            "description": "Legality of the card in the [Penny Dreadful](https://mtg.wiki/page/Penny_Dreadful) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "pioneer": {
            "description": "Legality of the card in the [Pioneer](https://magic.wizards.com/en/formats/pioneer) play format.",
            "introduced": "v4.6.0",
            "optional": True,
        },
        "predh": {
            "description": "Legality of the card in the [PreDH](https://articles.starcitygames.com/magic-the-gathering/commander-sub-format-predh-is-the-new-magic-rage/) play format.",
            "introduced": "v5.2.1",
            "optional": True,
        },
        "premodern": {
            "description": "Legality of the card in the [Premodern](https://premodernmagic.com/) play format.",
            "introduced": "v5.2.0",
            "optional": True,
        },
        "standard": {
            "description": "Legality of the card in the [Standard](https://magic.wizards.com/en/formats/standard) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "standardbrawl": {
            "description": "Legality of the card in the [Standard Brawl](https://magic.wizards.com/en/formats/brawl) play format.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "timeless": {
            "description": "Legality of the card in the [Timeless](https://magic.wizards.com/en/formats/timeless) play format.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "vintage": {
            "description": "Legality of the card in the [Vintage](https://magic.wizards.com/en/formats/vintage) play format.",
            "introduced": "v4.0.0",
            "optional": True,
        },
    }

    alchemy: str
    brawl: str
    commander: str
    duel: str
    explorer: str
    future: str
    gladiator: str
    historic: str
    historicbrawl: str
    legacy: str
    modern: str
    oathbreaker: str
    oldschool: str
    pauper: str
    paupercommander: str
    penny: str
    pioneer: str
    predh: str
    premodern: str
    standard: str
    standardbrawl: str
    timeless: str
    vintage: str


class PurchaseUrls(TypedDict, total=False):
    """Purchase URLs for a card."""

    __doc_title__ = "Purchase Urls"
    __doc_desc__ = (
        "The Purchase Urls Data Model describes the properties of links to purchase a product from a marketplace."
    )
    __doc_parent__ = (
        "**Parent model:** [Card (Atomic)](/data-models/card/card-atomic/), "
        "[Card (Deck)](/data-models/card/card-deck/), "
        "[Card (Set)](/data-models/card/card-set/)\n"
        "- **Parent property:** `purchaseUrls`"
    )
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, purchase urls"
    __field_docs__ = {
        "cardKingdom": {
            "description": "The URL to purchase a product on [Card Kingdom](https://www.cardkingdom.com?partner=mtgjson&utm_source=mtgjson&utm_medium=affiliate&utm_campaign=mtgjson).",
            "introduced": "v5.0.0",
            "optional": True,
        },
        "cardKingdomEtched": {
            "description": "The URL to purchase an etched product on [Card Kingdom](https://www.cardkingdom.com?partner=mtgjson&utm_source=mtgjson&utm_medium=affiliate&utm_campaign=mtgjson).",
            "introduced": "v5.2.0",
            "optional": True,
        },
        "cardKingdomFoil": {
            "description": "The URL to purchase a foil product on [Card Kingdom](https://www.cardkingdom.com?partner=mtgjson&utm_source=mtgjson&utm_medium=affiliate&utm_campaign=mtgjson).",
            "introduced": "v5.0.0",
            "optional": True,
        },
        "cardmarket": {
            "description": "The URL to purchase a product on [Cardmarket](https://www.cardmarket.com/en/Magic?utm_campaign=card_prices&utm_medium=text&utm_source=mtgjson).",
            "introduced": "v4.4.0",
            "optional": True,
        },
        "tcgplayer": {
            "description": "The URL to purchase a product on [TCGplayer](https://www.tcgplayer.com?partner=mtgjson&utm_campaign=affiliate&utm_medium=mtgjson&utm_source=mtgjson).",
            "introduced": "v4.4.0",
            "optional": True,
        },
        "tcgplayerEtched": {
            "description": "The URL to purchase an etched product on [TCGplayer](https://www.tcgplayer.com?partner=mtgjson&utm_campaign=affiliate&utm_medium=mtgjson&utm_source=mtgjson).",
            "introduced": "v5.2.0",
            "optional": True,
        },
    }

    cardKingdom: str
    cardKingdomEtched: str
    cardKingdomFoil: str
    cardmarket: str
    tcgplayer: str
    tcgplayerEtched: str


class RelatedCards(TypedDict, total=False):
    """Related cards (spellbook, reverse related, tokens)."""

    __doc_title__ = "Related Cards"
    __doc_desc__ = "The Related Cards Data Model describes the properties of a card that has relations to other cards."
    __doc_parent__ = (
        "**Parent model:** [Card (Atomic)](/data-models/card/card-atomic/), "
        "[Card (Deck)](/data-models/card/card-deck/), "
        "[Card (Set)](/data-models/card/card-set/), "
        "[Card (Token)](/data-models/card/card-token/)\n"
        "- **Parent property:** `relatedCards`"
    )
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, version, related cards"
    __field_docs__ = {
        "reverseRelated": {
            "description": 'A list of card names associated to a card, such as "meld" cards and token creation.',
            "introduced": "v5.2.1",
            "optional": True,
        },
        "spellbook": {
            "description": "A list of card names associated to a card's [Spellbook](https://mtg.wiki/page/Spellbook) mechanic.",
            "introduced": "v5.2.1",
            "optional": True,
        },
    }

    reverseRelated: list[str]
    spellbook: list[str]
    tokens: list[str]


class Rulings(TypedDict):
    """Card ruling entry."""

    __doc_title__ = "Rulings"
    __doc_desc__ = "The Rulings Data Model describes the properties of rulings for a card."
    __doc_parent__ = (
        "**Parent model:** [Card (Atomic)](/data-models/card/card-atomic/), "
        "[Card (Deck)](/data-models/card/card-deck/), "
        "[Card (Set)](/data-models/card/card-set/)\n"
        "- **Parent property:** `rulings`"
    )
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, rulings"
    __field_docs__ = {
        "date": {
            "description": "The release date in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format for the rule.",
            "introduced": "v4.0.0",
        },
        "text": {
            "description": "The text ruling of the card.",
            "introduced": "v4.0.0",
        },
    }

    date: str
    text: str


class SourceProducts(TypedDict, total=False):
    """Sealed products containing this card."""

    __doc_title__ = "Source Products"
    __doc_desc__ = "The Source Products Data Model describes the uuids for the card version in a Sealed Product."
    __doc_parent__ = (
        "**Parent model:** [Card (Set)](/data-models/card/card-set/)\n- **Parent property:** `sourceProducts`"
    )
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, source products"
    __field_docs__ = {
        "etched": {
            "description": "A list of universal unique identifiers (v5) generated by MTGJSON for the [Sealed Product](/data-models/sealed-product/) the etched card is found in.",
            "introduced": "v5.2.2",
        },
        "foil": {
            "description": "A list of universal unique identifiers (v5) generated by MTGJSON for the [Sealed Product](/data-models/sealed-product/) the foil card is found in.",
            "introduced": "v5.2.2",
        },
        "nonfoil": {
            "description": "A list of universal unique identifiers (v5) generated by MTGJSON for the [Sealed Product](/data-models/sealed-product/) the non-foil card is found in.",
            "introduced": "v5.2.2",
        },
    }

    etched: list[str]
    foil: list[str]
    nonfoil: list[str]


class TokenProductIdentifiers(TypedDict, total=False):
    """Identifiers for a token product."""

    tcgplayerProductId: str


class TokenProductPurchaseUrls(TypedDict, total=False):
    """Purchase URLs for a token product."""

    tcgplayer: str


class TokenProductPart(TypedDict, total=False):
    """A token face within a token product."""

    faceAttribute: list[str]
    uuid: Required[str]


class TokenProduct(TypedDict, total=False):
    """A real product printing of a token."""

    identifiers: TokenProductIdentifiers
    purchaseUrls: TokenProductPurchaseUrls
    tokenParts: list[TokenProductPart]


# =============================================================================
# Meta/Translations
# =============================================================================


class Meta(TypedDict):
    """MTGJSON file metadata."""

    __doc_title__ = "Meta"
    __doc_desc__ = "The Meta Data Model describes the properties of the MTGJSON application meta data."
    __doc_parent__ = "**Parent file:** [Meta](/downloads/all-files/#meta)\n- **Parent property:** `meta`, `data`"
    __doc_enum__ = "meta"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, version, meta"
    __field_docs__ = {
        "date": {
            "description": "The current release date in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format for the MTGJSON build.",
            "introduced": "v4.0.0",
            "enum_key": "date",
        },
        "version": {
            "description": "The current [SemVer](https://semver.org) version for the MTGJSON build appended with the build date.",
            "introduced": "v4.0.0",
            "enum_key": "version",
        },
    }

    date: str
    version: str


class Translations(TypedDict, total=False):
    """Set name translations by language."""

    __doc_title__ = "Translations"
    __doc_desc__ = "The Translations Data Model describes the properties of a [Set](/data-models/set/) or [Set List](/data-models/set-list/)'s name translated in various alternate languages."
    __doc_parent__ = "**Parent model:** [Set](/data-models/set/)\n- **Parent property:** `translations`"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, translations"
    __field_docs__ = {
        "AncientGreek": {
            "description": "The set name translation in Ancient Greek.",
            "introduced": "v4.6.0",
            "optional": True,
        },
        "Arabic": {"description": "The set name translation in Arabic.", "introduced": "v4.6.0", "optional": True},
        "ChineseSimplified": {
            "description": "The set name translation in Chinese Simplified.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "ChineseTraditional": {
            "description": "The set name translation in Chinese Traditional.",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "French": {"description": "The set name translation in French.", "introduced": "v4.0.0", "optional": True},
        "German": {"description": "The set name translation in German.", "introduced": "v4.0.0", "optional": True},
        "Hebrew": {"description": "The set name translation in Hebrew.", "introduced": "v4.6.0", "optional": True},
        "Italian": {"description": "The set name translation in Italian.", "introduced": "v4.0.0", "optional": True},
        "Japanese": {"description": "The set name translation in Japanese.", "introduced": "v4.0.0", "optional": True},
        "Korean": {"description": "The set name translation in Korean.", "introduced": "v4.0.0", "optional": True},
        "Latin": {"description": "The set name translation in Latin.", "introduced": "v4.6.0", "optional": True},
        "Phyrexian": {
            "description": "The set name translation in Phyrexian.",
            "introduced": "v4.7.0",
            "optional": True,
        },
        "PortugueseBrazil": {
            "description": "The set name translation in Portuguese (Brazil).",
            "introduced": "v4.0.0",
            "optional": True,
        },
        "Russian": {"description": "The set name translation in Russian.", "introduced": "v4.0.0", "optional": True},
        "Sanskrit": {"description": "The set name translation in Sanskrit.", "introduced": "v4.6.0", "optional": True},
        "Spanish": {"description": "The set name translation in Spanish.", "introduced": "v4.0.0", "optional": True},
    }

    AncientGreek: str | None
    Arabic: str | None
    ChineseSimplified: str | None
    ChineseTraditional: str | None
    French: str | None
    German: str | None
    Hebrew: str | None
    Italian: str | None
    Japanese: str | None
    Korean: str | None
    Latin: str | None
    Phyrexian: str | None
    PortugueseBrazil: str | None
    Russian: str | None
    Sanskrit: str | None
    Spanish: str | None


class TcgplayerSkus(TypedDict, total=False):
    """TCGPlayer SKU information."""

    __doc_title__ = "Tcgplayer Skus"
    __doc_desc__ = "The Tcgplayer Skus Data Model describes the properties of the [TCGplayer](https://www.tcgplayer.com/?partner=mtgjson&utm_campaign=affiliate&utm_medium=mtgjson&utm_source=mtgjson) SKUs for a product."
    __doc_parent__ = (
        "**Parent file:** [TcgplayerSkus](/downloads/all-files/#tcgplayerskus)\n- **Parent property:** `data`"
    )
    __doc_enum__ = "tcgplayerSkus"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, tcgplayer skus"
    __doc_extra__ = """::: info Accessing the data

When using an `TcgplayerSkus.json` file, the Tcgplayer Skus Data Model is accessed through a single index array where its parent property is the card's `uuid` property. Here is a reduced payload of the model as an example:

```TypeScript
{
  data: Record<string, TcgplayerSkus[]>;
}
```

and accessing the data would look like this:

```TypeScript
const tcgplayerSkus: TcgplayerSkus = data["00010d56-fe38-5e35-8aed-518019aa36a5"][0];
```

:::"""
    __field_docs__ = {
        "condition": {
            "description": "The condition of the card.",
            "introduced": "v5.1.0",
            "enum_key": "condition",
        },
        "finish": {
            "description": "The finish of the card.",
            "introduced": "v5.2.0",
            "enum_key": "finishes",
        },
        "language": {
            "description": "The language of the card.",
            "introduced": "v5.1.0",
            "enum_key": "language",
        },
        "printing": {
            "description": "The printing style of the card.",
            "introduced": "v5.1.0",
            "enum_key": "printing",
        },
        "productId": {
            "description": "The product identifier of the card.",
            "introduced": "v5.1.0",
            "type_override": "string",
        },
        "skuId": {
            "description": "The SKU identifier of the card.",
            "introduced": "v5.1.0",
            "type_override": "string",
        },
    }

    condition: Required[str]
    finish: str  # optional — only present on etched SKUs (~34K/5M)
    language: Required[str]
    printing: Required[str]
    productId: Required[int]
    skuId: Required[int]


# =============================================================================
# Booster Configuration
# =============================================================================


class BoosterSheet(TypedDict, total=False):
    """Single sheet in a booster configuration."""

    __doc_title__ = "Booster Sheet"
    __doc_desc__ = (
        "The Booster Sheet Data Model describes the properties of how a sheet of printed cards can be configured."
    )
    __doc_parent__ = (
        "**Parent model:** [Booster Config](/data-models/booster/booster-config/)\n- **Parent property:** `sheets`"
    )
    __doc_slug__ = "booster/booster-sheet"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, booster sheet, sheet"
    __field_docs__ = {
        "allowDuplicates": {
            "description": "If the sheet can be picked for cards in duplicates.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "balanceColors": {
            "description": "If the sheet needs to have it colors balanced.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "cards": {
            "description": "The cards in the sheet, where the key is the card `uuid` and value is its weight in the sheet.",
            "introduced": "v5.2.2",
        },
        "foil": {
            "description": "If the cards in the sheet are all foiled.",
            "introduced": "v5.2.2",
        },
        "fixed": {
            "description": 'If cards are garunteed to be in this sheet. Used for "Jump Start"-style products.',
            "introduced": "v5.2.2",
            "optional": True,
        },
        "totalWeight": {
            "description": "Total weight of the sheet.",
            "introduced": "v5.2.2",
        },
    }

    allowDuplicates: bool
    balanceColors: bool
    cards: Required[dict[str, int]]  # card_uuid -> weight
    foil: Required[bool]
    fixed: bool
    totalWeight: Required[int]


class BoosterPack(TypedDict):
    """Single booster pack configuration."""

    __doc_title__ = "Booster Pack"
    __doc_desc__ = "The Booster Pack Data Model describes the properties of how a Booster Pack can be configured."
    __doc_parent__ = (
        "**Parent model:** [Booster Config](/data-models/booster/booster-config/)\n- **Parent property:** `boosters`"
    )
    __doc_slug__ = "booster/booster-pack"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, booster pack, pack"
    __field_docs__ = {
        "contents": {
            "description": "The contents of the booster pack, where the key is the card slot and value is the weight.",
            "introduced": "v5.2.2",
            "type_override": "Partial<Record<string, number>>",
        },
        "weight": {
            "description": "The weight of the booster pack configuration.",
            "introduced": "v5.2.2",
        },
    }

    contents: dict[str, int]  # sheet_name -> count
    weight: int


class BoosterConfig(TypedDict, total=False):
    """Complete booster configuration for a set."""

    __doc_title__ = "Booster Config"
    __doc_desc__ = "The Booster Config Data Model describes the properties of how a [Set](/data-models/set/)'s booster data may be configured."
    __doc_parent__ = "**Parent model:** [Set](/data-models/set/)\n- **Parent property:** `booster`"
    __doc_slug__ = "booster/booster-config"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, booster config"
    __field_docs__ = {
        "boosters": {
            "description": "The booster packs configurations. See the [Booster (Pack)](/data-models/booster/booster-pack/) Data Model.",
            "introduced": "v5.2.2",
        },
        "boostersTotalWeight": {
            "description": "The weight of total booster pack configurations.",
            "introduced": "v5.2.2",
        },
        "name": {
            "description": "The name of the product, if applicable.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "sheets": {
            "description": "The sheets of cards in a printing where the key is the name of the sheet and value is the configuration. See the [Booster (Sheet)](/data-models/booster/booster-sheet/) Data Model.",
            "introduced": "v5.2.2",
        },
        "sourceSetCodes": {
            "description": "The set codes with which cards in this booster are selected from.",
            "introduced": "v5.2.2",
        },
    }

    boosters: Required[list[BoosterPack]]
    boostersTotalWeight: Required[int]
    name: str
    sheets: Required[dict[str, BoosterSheet]]
    sourceSetCodes: Required[list[str]]


# =============================================================================
# Price Data
# =============================================================================


class PricePoints(TypedDict, total=False):
    """Price points by finish type."""

    __doc_title__ = "Price Points"
    __doc_desc__ = "The Price Points Data Model describes the properties of a card's price provider prices."
    __doc_parent__ = (
        "**Parent model:** [Price List](/data-models/price/price-list/)\n- **Parent property:** `buylist`, `retail`"
    )
    __doc_slug__ = "price/price-points"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, price list"
    __field_docs__ = {
        "etched": {
            "description": "The card's etched product price, where the key is the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) date and value is its price.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "foil": {
            "description": "The card's foil product price, where the key is the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) date and value is its price.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "normal": {
            "description": "The card's normal product price, where the key is the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) date and value is its price.",
            "introduced": "v5.2.2",
            "optional": True,
        },
    }

    etched: dict[str, float]
    foil: dict[str, float]
    normal: dict[str, float]


class PriceList(TypedDict, total=False):
    """Price list from a provider."""

    __doc_title__ = "Price List"
    __doc_desc__ = (
        "The Price List Data Model describes the properties of a card providers list of buying and selling ability."
    )
    __doc_parent__ = (
        "**Parent model:** [Price Formats](/data-models/price/price-formats/)\n"
        "- **Parent property:** `cardhoarder`, `cardkingdom`, `cardmarket`, `cardsphere`, `tcgplayer`"
    )
    __doc_slug__ = "price/price-list"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, price provider"
    __field_docs__ = {
        "buylist": {
            "description": "A list of card type availability for selling cards to this provider. See the [Price Points](/data-models/price/price-points/) Data Model.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "currency": {
            "description": "The currency of prices listed.",
            "introduced": "v5.2.2",
        },
        "retail": {
            "description": "A list of card type availability for buying cards from this provider. See the [Price Points](/data-models/price/price-points/) Data Model.",
            "introduced": "v5.2.2",
            "optional": True,
        },
    }

    buylist: PricePoints
    currency: Required[str]
    retail: PricePoints


class PriceFormats(TypedDict, total=False):
    """Prices by format (paper/mtgo) and provider."""

    __doc_title__ = "Price Formats"
    __doc_desc__ = (
        "The Price Formats Data Model describes the properties of all product formats that the price providers provide."
    )
    __doc_parent__ = (
        "**Parent file:** [All Prices](/downloads/all-files/#allprices), "
        "[All Prices Today](/downloads/all-files/#allpricestoday)\n"
        "- **Parent property:** `data`"
    )
    __doc_slug__ = "price/price-formats"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, price providers"
    __field_docs__ = {
        "mtgo": {
            "description": "Card prices available to this card for MTGO products. See the [Price List](/data-models/price/price-list/) Data Model.",
            "introduced": "v5.2.2",
            "optional": True,
            "type_override": "Record<'cardhoarder', PriceList>",
        },
        "paper": {
            "description": "Card prices available to this card for paper products. See the [Price List](/data-models/price/price-list/) Data Model.",
            "introduced": "v5.2.2",
            "optional": True,
            "type_override": "Record<'cardkingdom' | 'cardmarket' | 'cardsphere' | 'tcgplayer', PriceList>",
        },
    }

    mtgo: dict[str, PriceList]
    paper: dict[str, PriceList]


# =============================================================================
# Sealed Product Contents
# =============================================================================


class SealedProductCard(TypedDict, total=False):
    """Card in sealed product."""

    __doc_title__ = "Sealed Product (Card)"
    __doc_desc__ = "The Sealed Product (Card) Data Model describes the card product configuration in the [Sealed Product Contents](/data-models/sealed-product/sealed-product-contents/) Data Model."
    __doc_parent__ = (
        "**Parent model:** [Sealed Product Contents](/data-models/sealed-product/sealed-product-contents/)\n"
        "- **Parent property:** `card`"
    )
    __doc_slug__ = "sealed-product/sealed-product-card"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, sealed product card"
    __field_docs__ = {
        "foil": {
            "description": "If the card is foiled.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "name": {
            "description": "The name of the card.",
            "introduced": "v5.2.2",
        },
        "number": {
            "description": "The card number.",
            "introduced": "v5.2.2",
        },
        "set": {
            "description": "The set code for the card.",
            "introduced": "v5.2.2",
        },
        "uuid": {
            "description": "The universal unique identifier (v5) generated by MTGJSON.",
            "introduced": "v5.2.2",
        },
    }

    finishes: list[str]
    foil: bool
    name: Required[str]
    number: Required[str]
    set: Required[str]
    uuid: Required[str]


class SealedProductDeck(TypedDict):
    """Deck in sealed product."""

    __doc_title__ = "Sealed Product (Deck)"
    __doc_desc__ = "The Sealed Product (Deck) Data Model describes the deck product configuration in the [Sealed Product Contents](/data-models/sealed-product/sealed-product-contents/) Data Model."
    __doc_parent__ = (
        "**Parent model:** [Sealed Product Contents](/data-models/sealed-product/sealed-product-contents/)\n"
        "- **Parent property:** `deck`"
    )
    __doc_slug__ = "sealed-product/sealed-product-deck"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, sealed product deck"
    __field_docs__ = {
        "name": {
            "description": "The name of the product.",
            "introduced": "v5.2.2",
        },
        "set": {
            "description": "The set code for the product.",
            "introduced": "v5.2.2",
        },
    }

    name: str
    set: str


class SealedProductOther(TypedDict):
    """Non-card item in sealed product."""

    __doc_title__ = "Sealed Product (Other)"
    __doc_desc__ = "The Sealed Product (Other) Data Model describes the obscure product configuration in the [Sealed Product Contents](/data-models/sealed-product/sealed-product-contents/) Data Model."
    __doc_parent__ = (
        "**Parent model:** [Sealed Product Contents](/data-models/sealed-product/sealed-product-contents/)\n"
        "- **Parent property:** `other`"
    )
    __doc_slug__ = "sealed-product/sealed-product-other"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, sealed product other"
    __field_docs__ = {
        "name": {
            "description": "The name of the product.",
            "introduced": "v5.2.2",
        },
    }

    name: str


class SealedProductPack(TypedDict):
    """Booster pack in sealed product."""

    __doc_title__ = "Sealed Product (Pack)"
    __doc_desc__ = "The Sealed Product (Pack) Data Model describes the sealed pack configuration in the [Sealed Product Contents](/data-models/sealed-product/sealed-product-contents/) Data Model."
    __doc_parent__ = (
        "**Parent model:** [Sealed Product Contents](/data-models/sealed-product/sealed-product-contents/)\n"
        "- **Parent property:** `pack`"
    )
    __doc_slug__ = "sealed-product/sealed-product-pack"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, sealed product pack"
    __field_docs__ = {
        "code": {
            "description": "The name for the configuration of the Booster for the pack. Used for identifying a [Booster Config](/data-models/booster/booster-config/) Data Model.",
            "introduced": "v5.2.2",
        },
        "set": {
            "description": "The set code for the product.",
            "introduced": "v5.2.2",
        },
    }

    code: str
    set: str


class SealedProductSealed(TypedDict, total=False):
    """Nested sealed product."""

    __doc_title__ = "Sealed Product (Sealed)"
    __doc_desc__ = "The Sealed Product (Sealed) Data Model describes the sealed product configuration in the [Sealed Product Contents](/data-models/sealed-product/sealed-product-contents/) Data Model."
    __doc_parent__ = (
        "**Parent model:** [Sealed Product Contents](/data-models/sealed-product/sealed-product-contents/)\n"
        "- **Parent property:** `sealed`"
    )
    __doc_slug__ = "sealed-product/sealed-product-sealed"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, sealed product sealed"
    __field_docs__ = {
        "count": {
            "description": "The count of inner products in the product. Applies to a product that contains multiple copies of the same product, such as the pack count in a Booster Box.",
            "introduced": "v5.2.2",
        },
        "name": {
            "description": "The name of the product.",
            "introduced": "v5.2.2",
        },
        "set": {
            "description": "The set code for the product.",
            "introduced": "v5.2.2",
        },
        "uuid": {
            "description": "The universal unique identifier (v5) generated by MTGJSON.",
            "introduced": "v5.2.2",
        },
    }

    count: Required[int]
    name: Required[str]
    set: Required[str]
    uuid: str


class SealedProductVariableConfig(TypedDict, total=False):
    """Variable configuration weights."""

    chance: int
    weight: int


class SealedProductVariableItem(TypedDict, total=False):
    """Single variable configuration option."""

    card: list[SealedProductCard]
    deck: list[SealedProductDeck]
    other: list[SealedProductOther]
    pack: list[SealedProductPack]
    sealed: list[SealedProductSealed]
    variable_config: list[SealedProductVariableConfig]


class SealedProductVariableEntry(TypedDict, total=False):
    """Variable contents entry with configs."""

    configs: list[SealedProductVariableItem]


class SealedProductContents(TypedDict, total=False):
    """All possible contents of a sealed product."""

    __doc_title__ = "Sealed Product Contents"
    __doc_desc__ = "The Sealed Product Contents Data Model describes the properties for the purchaseable product of a [Set](/data-models/set/) Data Model."
    __doc_parent__ = (
        "**Parent model:** [Sealed Product](/data-models/sealed-product/)\n- **Parent property:** `contents`"
    )
    __doc_slug__ = "sealed-product/sealed-product-contents"
    __doc_enum__ = "sealedProduct"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, sealed product config"
    __field_docs__ = {
        "card": {
            "description": "The card configuration for a sealed card product. See the [Sealed Product (Card)](/data-models/sealed-product/sealed-product-card/) Data Model.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "deck": {
            "description": "The deck configuration for a sealed deck product. See the [Sealed Product (Deck)](/data-models/sealed-product/sealed-product-deck/) Data Model.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "other": {
            "description": "The product configuration for an obscure sealed product, such as a Spindown counter. See the [Sealed Product (Other)](/data-models/sealed-product/sealed-product-other/) Data Model.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "pack": {
            "description": "The pack configuration for a sealed booster pack product. See the [Sealed Product (Pack)](/data-models/sealed-product/sealed-product-pack/) Data Model.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "sealed": {
            "description": "The sealed configuration for a sealed product, such as a booster box. See the [Sealed Product (Sealed)](/data-models/sealed-product/sealed-product-sealed/) Data Model.",
            "introduced": "v5.2.2",
            "optional": True,
        },
        "variable": {
            "description": "The variable configurations for sealed products when the contents are not always pre-determined. This data type can be referenced on this Data Model",
            "introduced": "v5.2.2",
            "optional": True,
            "type_override": 'Record<"configs", SealedProductContents[]>[]',
        },
    }

    card: list[SealedProductCard]
    deck: list[SealedProductDeck]
    other: list[SealedProductOther]
    pack: list[SealedProductPack]
    sealed: list[SealedProductSealed]
    variable: list[SealedProductVariableEntry]


# =============================================================================
# Compiled Data Structures
# =============================================================================


class Keywords(TypedDict):
    """All keyword types in MTG."""

    __doc_title__ = "Keywords"
    __doc_desc__ = "The Keywords Data Model describes the properties of keywords available to any card."
    __doc_parent__ = "**Parent file:** [Keywords](/downloads/all-files/#keywords)\n- **Parent property:** `data`"
    __doc_enum__ = "keywords"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, keywords"
    __field_docs__ = {
        "abilityWords": {
            "description": "A list of ability words found in rules text on cards.",
            "introduced": "v4.3.0",
            "enum_key": "abilityWords",
        },
        "keywordAbilities": {
            "description": "A list of keyword abilities found in rules text on cards.",
            "introduced": "v4.3.0",
            "enum_key": "keywordAbilities",
        },
        "keywordActions": {
            "description": "A list of keyword actions found in rules text on cards.",
            "introduced": "v4.3.0",
            "enum_key": "keywordActions",
        },
    }

    abilityWords: list[str]
    keywordAbilities: list[str]
    keywordActions: list[str]


class CardType(TypedDict):
    """Type with its valid subtypes and supertypes."""

    __doc_title__ = "Card Type"
    __doc_desc__ = "The Card Type Data Model describes the properties of any possible subtypes and supertypes of a [CardType](/data-models/card-type/) Data Model."
    __doc_parent__ = (
        "**Parent model:** [CardTypes](/data-models/card-types/)\n"
        "- **Parent property:** `artifact`, `conspiracy`, `creature`, `enchantment`, "
        "`instant`, `land`, `phenomenon`, `plane`, `planeswalker`, `scheme`, "
        "`sorcery`, `tribal`, `vanguard`"
    )
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, card type"
    __field_docs__ = {
        "subTypes": {
            "description": "A list of subtypes associated to a card property.",
            "introduced": "v4.0.0",
        },
        "superTypes": {
            "description": "A list of supertypes associated to a card property.",
            "introduced": "v4.0.0",
        },
    }

    subTypes: list[str]
    superTypes: list[str]


class CardTypes(TypedDict):
    """All card types and their valid sub/supertypes."""

    __doc_title__ = "Card Types"
    __doc_desc__ = "The Card Types Data Model describes the properties of a Card Data Model that has possible confurations of associated subtypes and supertypes."
    __doc_parent__ = "**Parent file:** [CardTypes](/downloads/all-files/#cardtypes)\n- **Parent property:** `data`"
    __doc_keywords__ = "mtg, magic the gathering, mtgjson, json, card types"
    __field_docs__ = {
        "artifact": {"description": "The artifact type of a card.", "introduced": "v4.0.0"},
        "battle": {"description": "The battle type of a card.", "introduced": "v5.2.2"},
        "conspiracy": {"description": "The artifact type of a card.", "introduced": "v4.0.0"},
        "creature": {"description": "The creature type of a card.", "introduced": "v4.0.0"},
        "enchantment": {"description": "The enchantment type of a card.", "introduced": "v4.0.0"},
        "instant": {"description": "The instant type of a card.", "introduced": "v4.0.0"},
        "land": {"description": "The land type of a card.", "introduced": "v4.0.0"},
        "phenomenon": {"description": "The phenomenon type of a card.", "introduced": "v4.0.0"},
        "plane": {"description": "The plane type of a card.", "introduced": "v4.0.0"},
        "planeswalker": {"description": "The planeswalker type of a card.", "introduced": "v4.0.0"},
        "scheme": {"description": "The scheme type of a card.", "introduced": "v4.0.0"},
        "sorcery": {"description": "The sorcery type of a card.", "introduced": "v4.0.0"},
        "tribal": {"description": "The tribal type of a card.", "introduced": "v4.0.0"},
        "vanguard": {"description": "The vanguard type of a card.", "introduced": "v4.0.0"},
    }

    artifact: CardType
    battle: CardType
    conspiracy: CardType
    creature: CardType
    enchantment: CardType
    instant: CardType
    land: CardType
    phenomenon: CardType
    plane: CardType
    planeswalker: CardType
    scheme: CardType
    sorcery: CardType
    tribal: CardType
    vanguard: CardType


# =============================================================================
# Registry for TypeScript generation
# =============================================================================

TYPEDDICT_REGISTRY: list[type] = [
    # Core card sub-models
    ForeignDataIdentifiers,
    ForeignData,
    Identifiers,
    LeadershipSkills,
    Legalities,
    PurchaseUrls,
    RelatedCards,
    Rulings,
    SourceProducts,
    TokenProductIdentifiers,
    TokenProductPurchaseUrls,
    TokenProductPart,
    TokenProduct,
    # Meta/translations
    Meta,
    Translations,
    TcgplayerSkus,
    # Booster
    BoosterSheet,
    BoosterPack,
    BoosterConfig,
    # Prices
    PricePoints,
    PriceList,
    PriceFormats,
    # Sealed product contents
    SealedProductCard,
    SealedProductDeck,
    SealedProductOther,
    SealedProductPack,
    SealedProductSealed,
    SealedProductVariableConfig,
    SealedProductVariableItem,
    SealedProductVariableEntry,
    SealedProductContents,
    # Compiled
    Keywords,
    CardType,
    CardTypes,
]
