sudo: true
dist: xenial

language: python
python: "3.7"
cache: pip

before_install:
  - pip install -U pip setuptools wheel

install:
  - pip install -r requirements.txt -r requirements_test.txt

script:
  - pytest
  - black --check --diff .
  - pylint mtgjson4 tests
  - mypy .
  - npx eclint check $(git ls-files)
