language: python
python:
  - "3.6"
cache: pip
install:
  - travis_retry pip install -r requirements.txt
script:
  # - pylint mtgjson4 tests
  - pytest
  - mypy --ignore-missing-imports --disallow-untyped-calls --disallow-incomplete-defs .
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    on_success: never
