"""MTGJSON Identifiers Object model for cross-platform card identifiers."""

from typing import Any, Dict

from pydantic import Field, field_validator

from ..mtgjson_base import MTGJsonModel


class MtgjsonIdentifiersObject(MTGJsonModel):
    """
    The Identifiers Data Model describes the properties of identifiers associated to a card or product.
    """

    abu_id: str | None = Field(default=None, description="The ABUGames identifier.")
    card_kingdom_etched_id: str | None = Field(
        default=None, description="The Card Kingdom etched card identifier."
    )
    card_kingdom_foil_id: str | None = Field(
        default=None, description="The Card Kingdom foil card identifier."
    )
    card_kingdom_id: str | None = Field(
        default=None, description="The Card Kingdom card identifier."
    )
    cardsphere_id: str | None = Field(
        default=None, description="The Cardsphere card identifier."
    )
    cardsphere_foil_id: str | None = Field(
        default=None, description="The Cardsphere foil card identifier."
    )
    cardtrader_id: str | None = Field(
        default=None, description="The Card Trader card identifier."
    )
    csi_id: str | None = Field(default=None, description="The CoolStuffInc identifier.")
    mcm_id: str | None = Field(
        default=None,
        description="The Cardmarket card identifier.",
    )
    mcm_meta_id: str | None = Field(
        default=None, description="The Cardmarket card meta identifier."
    )
    miniaturemarket_id: str | None = Field(
        default=None, description="The Miniature Market identifier."
    )
    mtg_arena_id: str | None = Field(
        default=None,
        description="The Magic: The Gathering Arena card identifier.",
    )
    mtgjson_foil_version_id: str | None = Field(
        default=None,
        description="The universal unique identifier (v4) generated by MTGJSON for the foil version of the card.",
    )
    mtgjson_non_foil_version_id: str | None = Field(
        default=None,
        description="The universal unique identifier (v4) generated by MTGJSON for the non-foil version of the card.",
    )
    mtgjson_v4_id: str | None = Field(
        default=None,
        description="The universal unique identifier (v4) generated by MTGJSON.",
    )
    mtgo_foil_id: str | None = Field(
        default=None,
        description="The Magic: The Gathering Online card foil identifier.",
    )
    mtgo_id: str | None = Field(
        default=None, description="The Magic: The Gathering Online card identifier."
    )
    multiverse_id: str | None = Field(
        default=None,
        description="The Wizards of the Coast card identifier used in conjunction with Gatherer.",
    )
    scg_id: str | None = Field(
        default=None, description="The StarCityGames identifier."
    )
    scryfall_id: str | None = Field(
        default=None,
        validation_alias="id",
        description="The universal unique identifier generated by Scryfall. Note that cards with multiple faces are not unique.",
    )
    scryfall_card_back_id: str | None = Field(
        default=None,
        validation_alias="card_back_id",
        description="The universal unique identifier generated by Scryfall for the back face of a card.",
    )
    scryfall_oracle_id: str | None = Field(
        default=None,
        validation_alias="oracle_id",
        description="The unique identifier generated by Scryfall for this card's oracle identity.",
    )
    scryfall_illustration_id: str | None = Field(
        default=None,
        validation_alias="illustration_id",
        description="The unique identifier generated by Scryfall for the card artwork that remains consistent across reprints.",
    )
    tcgplayer_product_id: str | None = Field(
        default=None, description="The TCGplayer card identifier."
    )
    tcgplayer_etched_product_id: str | None = Field(
        default=None,
        description="The TCGplayer etched card identifier.",
    )
    tnt_id: str | None = Field(
        default=None, description="The Troll and Toad identifier."
    )

    @field_validator(
        "mtgo_id",
        "mtgo_foil_id",
        "mtg_arena_id",
        "tcgplayer_product_id",
        "tcgplayer_etched_product_id",
        "mcm_id",
        mode="before",
    )
    @classmethod
    def convert_numeric_ids_to_string(cls, v: Any) -> str | None:
        """Convert numeric IDs to strings (Scryfall provides numbers, MTGJSON uses strings)"""
        if v is None:
            return None
        return str(v)

    @field_validator("multiverse_id", mode="before")
    @classmethod
    def extract_first_multiverse_id(cls, v: Any) -> str | None:
        """Extract first element from multiverse_ids array (Scryfall uses array, MTGJSON uses single string)"""
        if v is None:
            return None
        if isinstance(v, list) and len(v) > 0:
            return str(v[0])
        if isinstance(v, str):
            return v
        return str(v)

    def to_json(self) -> Dict[str, str]:
        """
        Custom JSON serialization that filters out empty values
        :return: JSON object with non-empty values only
        """
        parent = super().to_json()
        return {key: value for key, value in parent.items() if value}
