"""MTGJSON Foreign Data Object model for localized card information."""

from typing import Any, Dict, Set

from pydantic import Field, field_validator

from ... import constants
from ..mtgjson_base import MTGJsonModel
from .mtgjson_identifiers import MtgjsonIdentifiersObject


class MtgjsonForeignDataObject(MTGJsonModel):
    """
    The Foreign Data Data Model describes the properties for a card in alternate languages.
    """

    face_name: str | None = Field(
        default=None,
        alias="printed_name",
        description="The foreign name on the face of the card.",
    )
    flavor_text: str | None = Field(
        default=None,
        alias="flavor_text",
        description="The foreign flavor text of the card.",
    )
    identifiers: MtgjsonIdentifiersObject = Field(
        default_factory=MtgjsonIdentifiersObject,
        description="The identifiers associated to a card.",
    )
    language: str = Field(
        default="", alias="lang", description="The foreign language of card."
    )
    multiverse_id: int | None = Field(
        default=None,
        alias="multiverse_ids",
        description="The Multiverse ID of the foreign card.",
    )
    name: str = Field(
        default="", alias="printed_name", description="The foreign name of the card."
    )
    text: str | None = Field(
        default=None, alias="printed_text", description="The foreign text of the card."
    )
    type: str | None = Field(
        default=None,
        alias="printed_type_line",
        description="The foreign type of the card, including any supertypes and subtypes.",
    )
    uuid: str = Field(
        default="",
        description="The universal unique identifier (v5) generated by MTGJSON.",
    )

    @field_validator("language", mode="before")
    @classmethod
    def map_language_code(cls, v: Any) -> str:
        """Map language code to full language name"""
        if not v:
            return "unknown"
        return constants.LANGUAGE_MAP.get(v, "unknown")

    @field_validator("multiverse_id", mode="before")
    @classmethod
    def extract_first_multiverse_id(cls, v: Any) -> int | None:
        """Extract first element from multiverse_ids array"""
        if v is None:
            return None
        if isinstance(v, list) and len(v) > 0:
            first_val = v[0]
            return int(first_val) if first_val is not None else None
        if isinstance(v, int):
            return v
        return None

    def build_keys_to_skip(self) -> Set[str]:
        """
        Keys to skip in JSON output
        :return: Set of keys to skip
        """
        return {"url", "number", "set_code"}

    def to_json(self) -> Dict[str, Any]:
        """
        Custom JSON serialization that filters out None values
        :return: JSON serialized object
        """
        parent = super().to_json()
        return {key: value for key, value in parent.items() if value is not None}
