"""
Class Dispatcher
"""

from mtgjson5.classes.mtgjson_card_obj import MtgjsonCardObject
from mtgjson5.classes.mtgjson_foreign_data_obj import MtgjsonForeignDataObject
from mtgjson5.classes.mtgjson_leadership_skills_obj import MtgjsonLeadershipSkillsObject
from mtgjson5.classes.mtgjson_legalities_obj import MtgjsonLegalitiesObject
from mtgjson5.classes.mtgjson_meta_obj import MtgjsonMetaObject
from mtgjson5.classes.mtgjson_prices_obj import MtgjsonPricesObject
from mtgjson5.classes.mtgjson_purchase_urls_obj import MtgjsonPurchaseUrlsObject
from mtgjson5.classes.mtgjson_rulings_obj import MtgjsonRulingObject
from mtgjson5.classes.mtgjson_set_obj import MtgjsonSetObject
from mtgjson5.classes.mtgjson_translations_obj import MtgjsonTranslationsObject
