"""
Pipeline stage modules.

Each module contains related transformations for a specific phase
of the card data pipeline.
"""

from mtgjson5.v2.pipeline.stages.basic_fields import (
    add_basic_fields,
    add_booster_types,
    add_card_attributes,
    add_mana_info,
    add_original_release_date,
    apply_card_enrichment,
    apply_watermark_overrides,
    filter_keywords_for_face,
    fix_manavalue_for_multiface,
    fix_power_toughness_for_multiface,
    fix_promo_types,
    format_planeswalker_text,
    parse_type_line_expr,
    propagate_watermark_to_faces,
)
from mtgjson5.v2.pipeline.stages.derived import (
    add_alternative_deck_limit,
    add_is_funny,
    add_is_timeshifted,
    add_purchase_urls_struct,
    add_rebalanced_linkage,
    add_secret_lair_subsets,
    add_source_products,
    apply_manual_overrides,
    calculate_duel_deck,
    link_foil_nonfoil_versions,
)
from mtgjson5.v2.pipeline.stages.explode import (
    assign_meld_sides,
    detect_aftermath_layout,
    explode_card_faces,
    update_meld_names,
)
from mtgjson5.v2.pipeline.stages.identifiers import (
    add_identifiers_struct,
    add_identifiers_v4_uuid,
    add_uuid_from_cache,
    fix_foreigndata_for_faces,
    join_cardmarket_ids,
    join_face_flavor_names,
    join_gatherer_data,
    join_identifiers,
    join_name_data,
    join_oracle_data,
    join_set_number_data,
)
from mtgjson5.v2.pipeline.stages.legalities import (
    add_availability_struct,
    add_legalities_struct,
    fix_availability_from_ids,
    remap_availability_values,
)
from mtgjson5.v2.pipeline.stages.metadata import (
    build_expanded_decks_df,
    build_sealed_products_lf,
    build_set_metadata_df,
)
from mtgjson5.v2.pipeline.stages.output import (
    dataframe_to_cards_list,
    drop_raw_scryfall_columns,
    filter_out_tokens,
    prepare_cards_for_json,
    rename_all_the_things,
    sink_cards,
)
from mtgjson5.v2.pipeline.stages.relationships import (
    add_leadership_skills_expr,
    add_other_face_ids,
    add_reverse_related,
    add_token_ids,
    add_variations,
    propagate_salt_to_tokens,
)
from mtgjson5.v2.pipeline.stages.signatures import (
    add_related_cards_from_context,
    add_signatures_combined,
    join_signatures,
)

__all__ = [
    "add_alternative_deck_limit",
    "add_availability_struct",
    "add_basic_fields",
    "add_booster_types",
    "add_card_attributes",
    "add_identifiers_struct",
    "add_identifiers_v4_uuid",
    "add_is_funny",
    "add_is_timeshifted",
    "add_leadership_skills_expr",
    "add_legalities_struct",
    "add_mana_info",
    "add_original_release_date",
    "add_other_face_ids",
    "add_purchase_urls_struct",
    "add_rebalanced_linkage",
    "add_related_cards_from_context",
    "add_reverse_related",
    "add_secret_lair_subsets",
    "add_signatures_combined",
    "add_source_products",
    "add_token_ids",
    "add_uuid_from_cache",
    "add_variations",
    "apply_card_enrichment",
    "apply_manual_overrides",
    "apply_watermark_overrides",
    "assign_meld_sides",
    "build_expanded_decks_df",
    "build_sealed_products_lf",
    "build_set_metadata_df",
    "calculate_duel_deck",
    "dataframe_to_cards_list",
    "detect_aftermath_layout",
    "drop_raw_scryfall_columns",
    "explode_card_faces",
    "filter_keywords_for_face",
    "filter_out_tokens",
    "fix_availability_from_ids",
    "fix_foreigndata_for_faces",
    "fix_manavalue_for_multiface",
    "fix_power_toughness_for_multiface",
    "fix_promo_types",
    "format_planeswalker_text",
    "join_cardmarket_ids",
    "join_face_flavor_names",
    "join_gatherer_data",
    "join_identifiers",
    "join_name_data",
    "join_oracle_data",
    "join_set_number_data",
    "join_signatures",
    "link_foil_nonfoil_versions",
    "parse_type_line_expr",
    "prepare_cards_for_json",
    "propagate_salt_to_tokens",
    "propagate_watermark_to_faces",
    "remap_availability_values",
    "rename_all_the_things",
    "sink_cards",
    "update_meld_names",
]
